# words.py

word_groups = {
     "Свойства человека": {
         "дурной, раздражительный": {"translations": ["bad-tempered", "quick-tempered"], "examples": ["Sam's been bad-tempered recently, is something worrying him? (всегда такой)", "He is quick-tempered and often loses his patience in stressful situations. (время от времени)"]},
         "весёлый": {"translations": ["cheerful"], "examples": ["I'm not feeling very cheerful today."]},
         "упрямый (+), настойчивый": {"translations": ["determined"], "examples": ["He's determined to win this match."]},
         "внимательный": {"translations": ["considerate"], "examples": ["a polite and considerate child"]},
         "откровенный": {"translations": ["frank"], "examples": ["To be frank, I don't really want to see him."]},
         "честный": {"translations": ["honest"], "examples": ["To be honest, I didn't really enjoy the party."]},
         "ленивый": {"translations": ["lazy"], "examples": ["You lazy thing!"]},
         "подлый": {"translations": ["mean"], "examples": ["I thought my sister was being mean to me."]},
         "эгоистичный": {"translations": ["selfish"], "examples": ["It's very selfish of him."]},
         "сочувствующий": {"translations": ["sympathetic"], "examples": ["My boss is very sympathetic about my situation."]},
         "спокойный": {"translations": ["patient", "calm", "placid"], "examples": ["You need to be patient with children.", "Try to stay calm - the doctor will be here soon.", "She has a placid personality and rarely gets upset, no matter what happens."]},
         "грубый": {"translations": ["abrasive", "rude", "nasty"], "examples": ["an abrasive manner (прямота, непринятие)", "He complained that a member of staff had been rude to him. (общий)", "She has a nasty temper. (мерзость"]},
         "жадный": {"translations": ["greedy"], "examples": ["They were greedy for money."]},
         "строгий": {"translations": ["strict"], "examples": ["My parents were very strict with us."]},
         "нежный": {"translations": ["gentle"], "examples": ["My mother was such a gentle, loving person."]},
         "застенчивый": {"translations": ["shy", "self-effacing"], "examples": ["He was too shy to say anything to her.", "The captain was typically self-effacing when questioned about the team's successes"]},
         "амбициозный": {"translations": ["ambitious"], "examples": ["an ambitious young lawyer"]},
         "завистливый": {"translations": ["jealous"], "examples": ["He had always been very jealous of his brother's good looks."]},
         "добрый": {"translations": ["kind"], "examples": ["Please be kind to your sister!"]},
         "благодарный": {"translations": ["grateful"], "examples": ["After the earthquake we felt grateful to be alive."]},
         "творческий": {"translations": ["imaginative"], "examples": ["an imaginative designer"]},
         "вежливый": {"translations": ["polite"], "examples": ["I'm afraid I wasn't very polite to her."]},
         "упрямый(-)": {"translations": ["stubborn"], "examples": ["They have huge arguments because they're both so stubborn."]},
         "старательный, дотошный": {"translations": ["painstaking", "conscientious"], "examples": ["He was described by his colleagues as a painstaking journalist.", "a conscientious student"]},
         "чувствительный": {"translations": ["sensitive"], "examples": ["Her reply showed that she was very sensitive to criticism."]},
         "щедрый": {"translations": ["generous"], "examples": ["a very generous man"]},
         "неуклюжий": {"translations": ["clumsy"], "examples": ["That's the third glass you've smashed this week - you're so clumsy!"]},
         "гордый": {"translations": ["proud"], "examples": ["You must be very proud of your son."]},
         "нервный": {"translations": ["tense", "nervous", "worried", "anxious"], "examples": ["1. Физическое беспокойство: He was tense before the big meeting", "2. Легкая тревого перед какой-то ситуацией: She felt nervous about her first day at work", "3. Глубокая озабоченность о прошедшем или будущем: I am worried about my friend's health", "4. Наиболее жесткая тревога: He is feeling anxious about the results of his medical tests."]},
         "надежный": {"translations": ["reliable", "trustworthy"], "examples": ["reliable information"]},
         "с широким кругозором": {"translations": ["broad-minded"], "examples": ["He is broadminded about the different forms families can take."]},
         "найзойливый человек": {"translations": ["busybody"], "examples": ["Some interfering busybody had rung the police."]},
         "циничный": {"translations": ["cynical"], "examples": ["She has a pretty cynical view of men.."]},
         "приземленный, разумный": {"translations": ["down to earth"], "examples": ["She's a down-to-earth woman with no pretensions."]},
         "человек, который любит общение": {"translations": ["extrovert"], "examples": ["Most sales people are extroverts."]},
         "человек, совмещающие экстроверта и интроверта": {"translations": ["ambivert"], "examples": ["An ambivert typically enjoys other people, but needs time alone."]},
         "человек, который не любит общение": {"translations": ["introvert"]},
         "доверчивый": {"translations": ["gullible"]},
         "предрассудительный, недалекий": {"translations": ["narrow-minded"], "examples": ["My uncle is so narrow-minded when it comes to using smartphones"]},
         "пунктуальный": {"translations": ["punctual"]},
         "замкнутый": {"translations": ["reserved"], "examples": ["The English have a reputation for being reserved."]},
         "самоуверенный": {"translations": ["self-confident", "self-assured"], "examples": ["She is self-confident enough to speak in front of a large audience.", "He is self-assured and always remains calm under pressure."]},
         "проницательный": {"translations": ["shrewd"], "examples": ["She is a shrewd politician who wants to avoid offending the electorate unnecessarily."]},
         "стеснительный человек": {"translations": ["shrinking violet"], "examples": ["She loves appearing on television and is no shrinking violet when it comes to expressing her views.."]},
         "тупой": {"translations": ["thick", "stupid", "silly"]},
         "безрассудный": {"translations": ["reckless"], "examples": ["He was found guilty of reckless driving."]},
         "преданный": {"translations": ["loyal", "devoted"], "examples": ["She has always been a loyal friend, standing by my side through every challenge I’ve faced.", "The devoted teacher spent extra hours after school helping her students understand the difficult subject."]},
     },
     
    "Состояние человека": {
        "восхищенный, пораженный": {"translations": ["excited", "startled"], "examples": ["And hobbling with a couple of sticks! — cries Phil, still more excited", "And he led the sad and startled children toward the sanitary unit."]},
        "прискорбный, огромная боль": {"translations": ["grievous"], "examples": ["It was a grievous head wound, and he was not expected to survive."]},
        "беспокойство": {"translations": ["concern", "anxiety"], "examples": ["The problem concerns us all", "She was ridden by anxiety"]},
        "нежелающий": {"translations": ["unwilling"], "examples": ["The two sides were unwilling to compromise"]},
        "уязвимость": {"translations": ["vulnerability"], "examples": ["You want a doctor who understands the patient's vulnerability"]},

    },
    
    "Глаголы для описания падения и роста параметров": {
        "резкое и катастрофическое падение (v)": {"translations": ["crash"], "examples": ["The stock market crashed after the news of a major economic crisis."]},
        "медленное и постепенное уменьшение (v)": {"translations": ["dwindle"], "examples": ["The company's profits have dwindled over the past few quarters."]},
        "стремительное падение (v)": {"translations": ["plummet", "plunge"], "examples": ["The value of the cryptocurrency plummeted overnight", "The temperature plunged to below freezing last night"]},
        "хаотичное и беспорядочное падение (v)": {"translations": ["tumble"], "examples": ["The stock prices tumbled after the release of poor earnings reports."]},
        "стагнация (v)": {"translations": ["flatline", "level off", "plateau"], "examples": ["The sales figures have flatlined for the past three months. (прекратиться полностью)", "After a period of rapid growth, the population levels off (выравнивание)", "The athlete's performance has plateaued despite intense training. (выравнивание поле роста)"]},
        "быстрое усиление или увеличение": {"translations": ["escalate", "skyrocket", "soar"], "examples": ["The conflict escalated into a full-scale war.", "The price of oil skyrocketed due to geopolitical tensions", "The company's shares soared after the announcement of strong quarterly results."]},
        "постепенное увеличение": {"translations": ["mount"], "examples": ["The pressure mounted as the deadline approached."]},
        "быстрый и внезапный рост": {"translations": ["mushroom"], "examples": ["The popularity of the new app mushroomed overnight."]},
        "перегнать": {"translations": ["overtake"], "examples": ["The car overtook another vehicle on the highway"]},
        "превосходить": {"translations": ["surpass", "outstrip"], "examples": ["The athlete surpassed the world record by 0.1 seconds", "The company's profits outstripped those of its competitors last year."]},
        "опережать": {"translations": ["outpace"], "examples": ["The economy is outpacing other countries in terms of growth."]},
        "ускорять": {"translations": ["precipitate", "accelerate"], "examples": ["Fear of losing her job precipitated her into action", "He accelerated the car"]},
    },
    
     "Искоренение, пропажа, поломка, дисфункция, прекращение, отзыв, удаление": {
         "искоренить": {"translations": ["eradicate"], "examples": ["The folk linguists' errors may thus seem nearly impossible to eradicate."]},
         "развалиться": {"translations": ["collapse", "crash"], "examples": ["The peace talks have collapsed."]},
         "разорение, опустошение": {"translations": ["devastation"], "examples": ["A recent hurricane devastated the city."]},
         "прекратить": {"translations": ["stop", "cease"], "examples": ["He ordered his men to cease firing.", "The company was forced to cease operations after accumulating massive debts."]},
         "отзывать, уходить, отступать": {"translations": ["withdraw", "back down"], "examples": ["The UN has withdrawn its troops from the country", "Local residents have forced the local council to back down from its plans to build a nightclub on their street"]},
         "поглощение одной компанией другой":  {"translations": ["takeover"], "examples": ["The company made a takeover bid for one of its rivals."]},
         "уйти с должности или бросить деятельность после многих лет": {"translations": ["bow out"], "examples": ["She'll be bowing out at the end of the month, after hosting the programme for eight years"]},
         "уйти на пенсию": {"translations": ["retire"], "examples": ["Since retiring from the company, she has done voluntary work for a charity."]},
         "свержение": {"translations": ["overthrow", "subvert"], "examples": ["He said that Allende's government in Chile was overthrown by the army and the CIA in 1973.", "The rebel army is attempting to subvert the government. (formal)"]},
         "подавлять": {"translations": ["suppress"], "examples": ["The Hungarian uprising in 1956 was suppressed by the Soviet Union."]},
         "крушение, крах": {"translations": ["downfall"], "examples": ["Rampant corruption brought about the downfall of the government."]},
         "срыв, поломка": {"translations": ["breakdown"], "examples": ["A breakdown in the peace talks"]},
         "остановить что-то, бросить": {"translations": ["stop", "give up"], "examples": ["Apparently she's stopped drinking", "I've given up trying to help her."]},
         "закрыть бизнес, фабрику": {"translations": ["shut down", "close down"], "examples": ["The factory was shut down due to environmental violations."]},
         "разориться (бизнес)": {"translations": ["fold", "go bankrupt"], "examples": ["Many small businesses fold within the first year.", "The recession has led to many small businesses going bankrupt."]},
         "удалить": {"translations": ["remove"], "examples": ["The men came to remove the rubbish from the backyard."]},
         "сдаваться": {"translations": ["give up", "surrender"], "examples": ["It is never too late to give up smoking", "It was shameful of them to surrender"]},
         "расторгать догоренности, отношения": {"translations": ["terminate"], "examples": ["The contract was terminated due to breach of terms."]},
         "разрушать": {"translations": ["destroy", "demolish", "ruin"], "examples": ["The war destroyed entire cities.", "The building was demolished (человеческими руками взорвано)", "The scandal ruined his political career."]},
         "отмена, отмена договоренностей": {"translations": ["cancel", "call off", "back out of", "revoke"], "examples": ["The men came to remove the rubbish from the backyard.", "if you call of a meeting", "The buyer backed out of the deal the day before they were due to sign the contract.", "The authorities have revoked their original decision to allow development of this rural area."]},
         "истощаться": {"translations": ["run out of"], "examples": ["I've run out of coffee"]},
     },
    "Вера, убеждение (духовное, внутренее, мистическое), следование, влиять": {
         "пророчество": {"translations": ["prophecy"], "examples": ["These doom and gloom prophecies are doing little to help the economy."]},
         "исполнять клятвы": {"translations": ["solve vows"], "examples": ["After years of misunderstanding, they finally managed to solve their vows by openly communicating and renewing their commitment to each other."]},
         "восприятие": {"translations": ["perception"], "examples": ["Her perception of the world changed completely after traveling to different countries and experiencing new cultures"]},
         "добродетель": {"translations": ["virtue"], "examples": ["Patience is a virtue that helps us navigate life's challenges with grace and understanding"]},
         "автономная единица, течение внутри религии": {"translations": ["denomination"], "examples": ["Christianity is composed of various denominations, such as Catholicism, Protestantism, and Orthodoxy, each with its own traditions and beliefs"]},
         "вера в что-то, убежденность в чём-то, установка": {"translations": ["belief", "conviction"], "examples": ["My belief is that hard work pays off in the long run. (personal experience or no proofs)", "Her conviction in the value of hard work helped her achieve her goals. (хотя бы какие-то доказательства)"]},
         "подражатель": {"translations": ["wannabee"], "examples": ["At the music concert, there were several wannabees dressed like rock stars, hoping to get noticed by the crowd."]},
         "предположение": {"translations": ["assumption"], "examples": ["The project failed because it was based on the assumption that all team members had access to the necessary resources."]},
         "убеждать (сделать что-то)": {"translations": ["persuade"], "examples": ["She tried to persuade her friend to join the hiking trip by describing the breathtaking views they would see along the way."]},
         "убеждать (идеи)": {"translations": ["convince"], "examples": ["She was convinced that he really loved her"]},
         "преданный, посвященный": {"translations": ["dedicated"], "examples": ["The Green Party is dedicated to protecting the environment."]},
         "влиять": {"translations": ["influence", "affect", "exert"], "examples": ["ПОЧИНИ СУКА environment."]},
         "стремление": {"translations": ["aspiration"], "examples": ["The Green Party is dedicated to protecting the environment."]},
         "намерение": {"translations": ["intention"], "examples": ["The Green Party is dedicated to protecting the environment."]},
         "воздействие": {"translations": ["impact"], "examples": ["We need to assess the impact on climate change"]},
    },

    "Катастрофы, бедствия, беды, несчастные случаи": {
         "потери из-за катастроф или войны": {"translations": ["casualties"], "examples": ["The train was derailed but there were no casualties, police said"]},
         "принимать меры предостороженности": {"translations": ["take precautions"], "examples": ["She took the precaution of packing extra medicine for the trip"]},
         "травмы": {"translations": ["injures"], "examples": ["A bomb exploded at the embassy, injuring several people"]},
         "толчок землетрясения": {"translations": ["tremor"], "examples": ["The tremor was felt as far as 200 miles away"]},
         "пепел": {"translations": ["ash"], "examples": ["cigarette ash"]},
         "беженцы": {"translations": ["refugee"], "examples": ["a refugee camp"]},
         "извержение вулкана": {"translations": ["volcanic eruption"], "examples": ["Around the year 600, the eruption of a nearby volcano buried Ceren's buildings"]},
         "проливной дождь": {"translations": ["torrential rain"], "examples": ["Torrential rain is very heavy rain."]},
         "ДТП": {"translations": ["traffic collision", "car crash", "car accident"], "examples": ["A serious traffic collision on the highway caused delays for several hours this morning.", "Fortunately, no one was injured in the car crash that occurred at the intersection.", "She filed an insurance claim after being involved in a minor car accident last week."]},
         "выходить из берегов (реки)": {"translations": ["burst banks"], "examples": ["Rivers burst their banks and flooded large areas, damaged roads."]},
         "цунами": {"translations": ["tsunami"], "examples": ["She left the area after she lost her house and her family in the tsunami."]},
         "лесной пожар": {"translations": ["wildfire", "bushfire", "forest fire"], "examples": ["The wildfire spread rapidly due to strong winds and dry vegetation.", "Australia experienced devastating bushfires during the summer, destroying thousands of hectares of land.", "A lightning strike was responsible for starting the forest fire in the national park."]},
         "землетрясение": {"translations": ["earthquake"], "examples": ["In 1906 an earthquake destroyed much of San Francisco."]},
         "молния": {"translations": ["lightning"], "examples": ["thunder and lightning"]},
         "оползень": {"translations": ["landslide"], "examples": ["Heavy rains triggered a massive landslide that blocked the main road leading to the village."]},
         "наводнение": {"translations": ["flood"], "examples": ["The whole town flooded when the river burst its banks."]},
         "засуха": {"translations": ["drought"], "examples": ["The drought severely impacted agricultural production in the region"]},
         "крушение самолета": {"translations": ["plane crash", "aircraft accident"], "examples": ["The plane crash occurred shortly after takeoff due to engine failure.", "Investigators are examining the wreckage to determine the cause of the aircraft accident."]},
         "сход поезда с рельс": {"translations": ["train derailment"], "examples": ["The train derailment resulted in several injuries and significant delays."]},
         "засуха": {"translations": ["drought"], "examples": ["The drought severely impacted agricultural production in the region"]},
         "ураган": {"translations": ["hurricane"], "examples": ["Hurricane Katrina caused catastrophic damage along the Gulf Coast."]},
         "шторм": {"translations": ["storm"], "examples": ["A lot of trees were blown down in the recent storms."]},
         "отключение электроэнергии": {"translations": ["power outage", "blackout"], "examples": ["A power outage affected millions of residents during the heatwave", "Power lines were blown down and we had a blackout of several hours."]},
    },

     "Здоровье": {
        "страдать от боли": {"translations": ["suffer", "afflict"], "examples": ["He suffers from headaches.", "The disease afflicts an estimated two million people every year."]},
        "сыпь": {"translations": ["rash"], "examples": ["Well, I've come out in a rash, and I can't get rid of it."]},
        "шишка": {"translations": ["lump"], "examples": ["Lumps can appear anywhere on your body."]},
        "прыщи": {"translations": ["spots"], "examples": ["Simon reeled and a white spot on his forehead turned red and trickled."]},
        "синяк": {"translations": ["black eye"], "examples": ["He had a pretty bad black eye after the bully punched him in the face."]},
        "Процесс взросления": {"translations": ["ageing process"], "examples": ["The ageing process refers to the inevitable natural progression of becoming older"]},
        "расти": {"translations": ["grow up"], "examples": ["Kids grow up fast these days"]},

     },
     
     "Закон, договоры, юриспрюденция, суд": {
         "отмена, отмена договоренностей": {"translations": ["cancel", "back out of", "revoke"], "examples": ["The men came to remove the rubbish from the backyard.", "The buyer backed out of the deal the day before they were due to sign the contract.", "The authorities have revoked their original decision to allow development of this rural area."]},
         "расторгать догоренности, отношения": {"translations": ["terminate"], "examples": ["The contract was terminated due to breach of terms."]},
         "договоры": {"translations": ["settlement", "treaty"], "examples": ["The dispute was resolved through a settlement (локальное)", "The dispute between the countries was resolved through a treaty. (глобальное)"]},
         "избирательное право": {"translations": ["suffrage"], "examples": ["universal suffrage"]},
         "опрос": {"translations": ["inquiry"], "examples": ["We've seen a rise in inquiries about insurance against flooding."]},
         },
         
     "Логика, время, логические связки, связки, переходы, метаморфозы, логические вводные слова": {
        "переход": {"translations": ["transition"], "examples": ["There will be an interim government to oversee the transition to democracy."]},
        "следовать": {"translations": ["follow", "ensue"], "examples": ["Just because I agreed last time, it doesn't necessarily follow that I will again.", "In the case of methods defined in the confining package, this ensues from the other confinement rules. (formal)"]},
        "предшествовать": {"translations": ["precede"], "examples": ["This task always preceded the word recognition task."]},
        "подтверждать": {"translations": ["confirm", "validate"], "examples": ["The young man's kindness confirmed her faith in young people.", "He feels that today's economic problems validate his opposition to the policy."]},
        "действительно": {"translations": ["indeed"], "examples": ["I am happy, indeed proud, to be associated with this project."]},
        "последствия": {"translations": ["consequences", "repercussions", "aftermath"], "examples": ["Not making a will can have serious consequences for your children and other family members.", "President Kennedy's assassination had far-reaching repercussions.", "Many more people died in the aftermath of the explosion. (период последствий)"]},
        "сравнение": {"translations": ["comparison"], "examples": [" They made a comparison of different countries' eating habits."]},
        "например": {"translations": ["for instance", "for exapmple"], "examples": ["In the electronics industry, for instance, 5,000 jobs are being lost."]},
        "сопровождать": {"translations": ["accompany"], "examples": ["The thunderstorm was accompanied by frequent lightning strikes and heavy rainfall."]},
        "в дальнейшем": {"translations": ["onwards"], "examples": ["From this point onwards, things started to improve."]},
        "после": {"translations": ["after", "afterwards"], "examples": ["Let's go for a walk after breakfast.", "We had tea, and afterwards we sat in the garden for a while."]},
        "исход": {"translations": ["outcome"], "examples": ["It's too early to predict the outcome of the meeting."]},
        "катализатор": {"translations": ["catalyst"], "examples": ["The high suicide rate acted as a catalyst for change in the prison system."]},
        "впоследствие": {"translations": ["subsequently"], "examples": ["In 1982 he was arrested and subsequently convicted on drug trafficking charges."]},
        "последующая": {"translations": ["subsequent"], "examples": ["The book discusses his illness and subsequent resignation from politics."]},
        "проще говоря": {"translations": ["put it simply"], "examples": ["Put it simply, the engine converts fuel into motion."]},
        "мягко говоря": {"translations": ["put it mildly"], "examples": ["The project was delayed — put it mildly, we missed the deadline."]},
        "прямо говоря": {"translations": ["put it bluntly"], "examples": ["Put it bluntly, your work is unacceptable."]},
        "короче": {"translations": ["in brief"], "examples": ["In brief, they were wrong and they have finally admitted it."]},
        "в двух словах": {"translations": ["in a nutshell"], "examples": ["In a nutshell, everything"]},
        "в конечном итоге": {"translations": ["all in all", "in total", "eventually"], "examples": ["The trip had its ups and downs, but all in all, it was a great experience.", "There were 20 people at the party last night — 10 men and 10 women, in total.", "It was a difficult journey, but eventually, we reached our destination."]},
        "очевидно": {"translations": ["apparently", "obviously"], "examples": ["Apparently it's going to rain today.", "He was in tears and obviously very upset."]},
        "наподобие": {"translations": ["likewise"], "examples": ["Likewise, we can reverse the roles of the left- and right-hand sides."]},
        "кардинально": {"translations": ["radically"], "examples": ["The accident radically changed the course of his life."]},
        "как правило": {"translations": ["as a rule"], "examples": ["As a general rule, I don't read detective novels."]},
        "кроме того": {"translations": ["by the way", "additionally"], "examples": ["Oh, by the way, my name's Julie.", "Additionally, we request a deposit of $200 in advance."]},
        "во имя чего-то": {"translations": ["in honor of"], "examples": ["The dinner is in honor of a colleague who is leaving."]},
        "буквально": {"translations": ["literally"], "examples": ["They were responsible for literally millions of deaths."]},
        "следовательно": {"translations": ["hence"], "examples": ["His mother was Italian, hence his name - Luca."]},
        "следствие чего-то": {"translations": ["implication"], "examples": ["From what she said, the implication was that they were splitting up."]},
        "именно (функция уточнения)": {"translations": ["namely"], "examples": ["I learned an important lesson when I lost my job, namely that nothing is a hundred percent guaranteed."]},
        "предпосылка": {"translations": ["prerequisite"], "examples": ["Passing a written test is a prerequisite for taking the advanced course."]},
        "найти источник чего-то": {"translations": ["trace"], "examples": ["The police are trying to trace the mother of a newborn baby found abandoned outside a hospital."]},
        "обобщение понятий": {"translations": ["generalisation"], "examples": ["Generalization can be dangerous."]},
        "качественно (наречие)": {"translations": ["qualitatively"], "examples": ["The successive levels differ qualitatively. (formal)"]},
        "соответствующая": {"translations": ["corresponding"], "examples": ["Company losses were 50 percent worse than in the corresponding period last year."]},
        "напротив": {"translations": ["on the contrary"], "examples": ["I'm not angry with you. On the contrary!"]},
        "ошибочная": {"translations": ["wrong", "false", "erroneous"], "examples": ["an wrong/false/erroneous belief/impression"]},
        "измененный": {"translations": ["altered"], "examples": ["She said her life was drastically altered."]},
        "обязательно влечёт, делает обязательным": {"translations": ["warrant"], "examples": ["ciObviously what she did was wrong, but I don't think it warranted such a severe punishment."]},
        "умеренно": {"translations": ["moderately"], "examples": ["There's very little moderately priced housing in this area."]},
        "развиваться, идти (ситуация)": {"translations": ["go for"], "examples": ["Things have gone badly for him since his business collapsed"]},
        "составлять": {"translations": ["be account for"], "examples": ["Oil accounts for 40% of Norway's exports."]},   
        "последовательность, согласованность, постоянство": {"translations": ["consistency"], "examples": ["Customers expect consistency in the quality of service they receive."]},
        "до, перед каким-то событием": {"translations": ["prior to"], "examples": ["Prior to going back to school, he worked in a restaurant."]},
        "ответственен за что-то (внедрение, изобретение), приписываемый": {"translations": ["credited"], "examples": ["Guteberg is often credited with invention of printig…"]},
        "логически складываться, объясняться": {"translations": ["add up"], "examples": ["I listened to Jill's explanation, but I'm still skeptical—something just doesn't add up."]},
        "решительно": {"translations": ["emphatically"], "examples": ["He has always emphatically denied the allegations against him"]},
        "подряд": {"translations": ["in a row"], "examples": ["He hit several fouls in a row"]},
        "в основном потому что": {"translations": ["mainly because"], "examples": ["I don't buy into it, mainly because I don't believe I have a soul to be saved"]},
        "В настоящее время (оттенок скоро)": {"translations": ["presently"], "examples": ["The range of courses presently available has grown"]},
        "В настоящее время": {"translations": ["currently"], "examples": ["He is currently working on his first novel"]},
        "За исключением (=if there are no)": {"translations": ["barring"], "examples": ["We should arrive at ten o'clock, barring any (= if there are no) unexpected delays"]},
        "в другом месте (где-либо)": {"translations": ["elsewhere"], "examples": ["I can speak with you here as well as elsewhere"]},
        "едва-ли": {"translations": ["scarcely"], "examples": ["I could scarcely believe it when she said she wanted to marry me"]}, 
        "неизбежный": {"translations": ["inevitable"], "examples": ["inevitable"]},
        "именно так": {"translations": ["precisely"], "examples": ["I am going to do precisely that"]},

     },
    
    "Предположения, определения": {
        "подразумевать": {"translations": ["assume", "imply"], "examples": ["We assume the train will be on time.", "His words implied that he wasn’t happy with the results."]},
        "предполагать": {"translations": ["suppose"], "examples": ["I suppose it might rain later."]},
        #foretell, 
    },

     "Думать, синтезировать, создавать, появляться, соединиться, начинать": {
        "возникать, появляться": {"translations": ["emerge", "appear"], "examples": ["New business opportunities will emerge with advances in technology.", "I've noticed that smaller cars are starting to appear"]},
        "возникать (история, факты)": {"translations": ["originate"], "examples": ["The game is thought to have originated among the native peoples of Alaska."]},
        "объединить, соединить": {"translations": ["put together", "amalgamate", "coalesce"], "examples": ["It took several hours to put the puzzle together.", "The electricians' union is planning to amalgamate with the technicians' union.", "The theory is that galaxies coalesced from smaller groupings of stars."]},
        "на данном этапе": {"translations": ["at this juncture"], "examples": ["At this juncture, it is impossible to say whether she will make a full recovery."]},
        "объединение": {"translations": ["amalgamation", "union"], "examples": ["The association was formed by the amalgamation of several regional environmental organizations (процесс)", "Meanwhile the debate on European political and monetary union continues."]},
        "основать": {"translations": ["set up", "found"], "examples": ["A committee has been set up to organize social events for the students.", "Boston was founded in 1630 by Puritan colonists from England."]},
        "слить воедино (трудно рассоединить)": {"translations": ["interweave"], "examples": ["She has created an intriguing story by skilfully interweaving fictional and historical events."]},
        "публиковатьья, выходить в свет": {"translations": ["publish", "come out"], "examples": ["We will publish our findings this year", " But when does this full book come out"]},
        "затевать": {"translations": ["contrive"], "examples": ["Somehow she contrived to get tickets for the concert"]},
        "размышлять": {"translations": ["reflect"], "examples": ["He reflected that he had no right to do this"]},
        "укорениться": {"translations": ["engrain", "take root"], "examples": ["The smell of fresh pine trees is engrained in the air of the forest", "Economists believe that economic recovery will begin to take root next year"]},
        "начать активность, занимать время": {"translations": ["take up"], "examples": ["The smell of fresh pine trees is engrained in the air of the forest", "Economists believe that economic recovery will begin to take root next year"]},
    },

    "Книги, фильмы, культура": {
        "полный действия": {"translations": ["action-packed"], "examples": ["an action-packed thriller/weekend/finale"]},
        "книга или фильм, которая очень сильно увлекает": {"translations": ["addictive"], "examples": ["This novel is so addictive that I stayed up all night reading it!"]},
        "книга или фильм, который вызывает много чувств": {"translations": ["intense"], "examples": ["1984 by George Orwell is an intense exploration of a dystopian society where freedom is suppressed and fear reigns supreme."]},
        "книга, которую ты не можешь остановиться читать": {"translations": ["page-turner"], "examples": ["Her latest novel is a real page-turner."]},
        "читать между строк": {"translations": ["read between the lines"], "examples": ["He gave a very diplomatic explanation, but if you read between the lines, it seems like he was fired for political reasons."]},
        "судить книгу по обложке": {"translations": ["judge a book by it's cover"], "examples": ["I know she dresses a little frumpy, but don't judge a book by its cover, man!"]},
        "книжный червь": {"translations": ["bookworm"], "examples": ["Emma's a real bookworm. You're more likely to find her curled up with a book on a Friday night than out at a party."]},
        "читать кого-то как книгу": {"translations": ["read someone like a book"], "examples": ["You won't be a very successful thief with that nervous demeanor—the cops will read you like a book."]},
        "потеряться в книге": {"translations": ["to get lost in a book"], "examples": ["I love curling up on the sofa and getting lost in a book."]},
        "роман": {"translations": ["novel"], "examples": ["the novel the literary genre represented by novels"]},

    },
    
    "Застять, застопориться": {
        "Застрять в бездействии": {"translations": ["stuck in a rut"], "examples": ["I had so many ambitions when I first graduated from college, but now I feel like I'm in a rut."]},
        "книга или фильм, которая очень сильно увлекает": {"translations": ["addictive"], "examples": ["This novel is so addictive that I stayed up all night reading it!"]},
        "колебаться": {"translations": ["hesitate"], "examples": ["She hesitated slightly before answering the detective's question."]},
    },
    
    "Экономика, деньги, финансы": {
        "жить по средствам": {"translations": ["live within ones means"], "examples": ["You need to start living within your means and avoid making so many frivolous purchases."]},
        "дешеветь": {"translations": ["come down"], "examples": ["I hope house prices in this neighborhood come down so that we can actually afford one."]},
        "неприлично богатый": {"translations": ["filthy rich"], "examples": ["Are you striving to become filthy rich in the competitive business world?"]},
        "неэффективный": {"translations": ["underperfoming"], "examples": ["organizations have a strategy around underperforming employees, specifically leaders?"]},
    },
    
    "Прилагательные": {
        "шлифовочный, абразивный": {"translations": ["abrasive"], "examples": ["An abrasive is a material, often a mineral, that is used to shape or finish a workpiece through rubbing"]},
        "недостижимый для понимания, бездонный": {"translations": ["fathomless"], "examples": ["The fathomless blue of Bliss"]},
        "современный, авангардный (искусство)": {"translations": ["contemporary"], "examples": ["Contemporary minds and rock groove together."]},
        "межвоенный": {"translations": ["interwar"], "examples": ["The interwar period (interbellum) lasted from 11 November 1918 to 1 September 1939"]},
        "широко распространенный": {"translations": ["widespread"], "examples": ["It is disturbing to find evidence of widespread corruption"]},
        "острый": {"translations": ["acute"], "examples": ["The war has aggravated an acute economic crisis"]},
        "отмеченный": {"translations": ["marked"], "examples": ["The corrections were marked in red"]},
        "назревший": {"translations": ["matured"], "examples": ["She has matured into a fine writer"]},
        "значительный": {"translations": ["significant"], "examples": ["He won a significant amount of money"]},
        "присущий": {"translations": ["inherent"], "examples": ["He has an inherent sense of fair play"]},
        "подлинный": {"translations": ["genuine"], "examples": ["The painting was authenticated as genuine"]},
        "бесспорный": {"translations": ["undeniable", "undoubtable"], "examples": ["The band's popularity is undeniable", "As for combat operations, Damascus' victory is undoubtable"]},
        "заметный, реальный, осязаемый": {"translations": ["tangible"], "examples": ["The silence of the countryside was almost tangible"]},
        "не требующий доказательств": {"translations": ["axiomatic"], "examples": ["It is axiomatic that good athletes have a strong mental attitude"]},
        "страшный": {"translations": ["creepy", "scary"], "examples": ["I think it's sort of creepy how people lurk in chat rooms", "The little girl was spooked by scary masks"]},
        "удобный": {"translations": ["comfortable", "convenient"], "examples": ["We hope that you are comfortable", "Is three o'clock convenient for you?"]},
        "громадный": {"translations": ["enormous", "imposing"], "examples": ["They live in an enormous house", "He's an imposing man with a powerful voice"]},
        "ошеломляющий": {"translations": ["stunning"], "examples": ["Our room had a stunning view of the lake"]},
        "свойство, когда в одной вещи сливаются стили, взгляды, идеи из разных областей": {"translations": ["eclectic"], "examples": ["The collection includes an eclectic mix of historical artifacts"]},
    },
    
    "Социальные отношения": {
        "поддерживать сторону в конфликте": {"translations": ["come down"], "examples": ["The government has come down on the side of military action"]},
        "становится популярным": {"translations": ["catch on"], "examples": ["I wonder if the game will ever catch on with young people"]},
        "сливаться со средой": {"translations": ["blend in"], "examples": ["Don't wear anything too flashy—try to blend into the background"]},
        "потакать, чтобы улучшить настроение человека": {"translations": ["humor"], "examples": ["Phil seems a bit cranky today, so just humor him"]},
        "полагаться на кого-то, что-то": {"translations": ["rely on"], "examples": ["For decorating, they rely on her discerning eye"]},
        "укреплять": {"translations": ["reinforce"], "examples": ["They had to reinforce the center"]},
        "общественная позиция": {"translations": ["stance"], "examples": ["California has adopted a tough stance on the issue"]},
        "шумная группа людей": {"translations": ["gaggle"], "examples": ["Fore the stranger there swarmed a gaggle of curious street urchins"]},
        "враждебность": {"translations": ["hostility"], "examples": ["They eyed each other with open hostility"]},
        "неравенство": {"translations": ["disparity"], "examples": ["It shows a huge disparity between the number missing and investigations undertaken"]},
        "противостоять": {"translations": ["confront"], "examples": ["You must confront your opponent"]},
        "поручать, передавать": {"translations": ["consign"], "examples": ["the shipment of apples was consigned to London"]},
        "взращивать": {"translations": ["bring up"], "examples": ["I was brought up to respect the law"]},
        "возмущаться": {"translations": ["resent"], "examples": ["Paul resented the fact that Carol didn't trust him"]},
        "осуждать": {"translations": ["condemn"], "examples": ["The whole town condemned the girl for her wild behaviour"]},
        "восхищаться, уважать": {"translations": ["look up to", "respect", "admire"], "examples": ["I've always looked up to Bill for his courage and determination", "We should respect the environment", "I admire his honesty"]},
        "распространять": {"translations": ["spread"], "examples": ["He spread his arms wide"]}
    },
    
    "Поиск, изучение, открытие, учеба": {
        "наткнуться, случайно найти что-то": {"translations": ["come across"], "examples": ["He came across some of his old love letters in his wife's desk"]},
        "Пронюхать что-то": {"translations": ["get wind"], "examples": ["I don't want my colleagues to get wind of the fact that I'm leaving"]},
        "колебаться": {"translations": ["hesitate"], "examples": ["She hesitated slightly before answering the detective's question"]},
        "исследовать, изучать": {"translations": ["examine", "research"], "examples": ["The customs agent examined the baggage", "I'm researching marketing strategies in medicine"]},
        "учиться через опыт": {"translations": ["pick up"], "examples": ["I picked up experience in graphic design by working on small freelance projects during college"]}
    },
    
    "Счастье, благополучие": {
        "процветание": {"translations": ["prosperity"], "examples": ["The town's nineteenth-century prosperity was built on steel"]},
        "страсть": {"translations": ["passion"], "examples": ["ThisShe is driven by her passion"]},
        "колебаться": {"translations": ["hesitate"], "examples": ["She hesitated slightly before answering the detective's question."]},
    },
    
    "Общие физические взаимодействия": {
        "Держаться за что-то или кого-то": {"translations": ["cling to"], "examples": ["She clung to the handrail as she walked down the slippery steps"]},
        "гулять, бродить, посещать": {"translations": ["stroll"], "examples": ["Stroll into the team meeting ready to share your insights and suggestions"]},
        "задушить (в том числе и переносное значение)": {"translations": ["suffocate"], "examples": ["The victims were found suffocated", "Jealousy can suffocate any relationship"]},
        "отталкивать": {"translations": ["repel"], "examples": ["Two positive charges repel each other"]},
        "идти вниз, нисходить": {"translations": ["descend"], "examples": ["The path descended steeply into the valley"]},
        "бродить туда-сюда": {"translations": ["pace"], "examples": ["He paced the room nervously"]},
        "отражать": {"translations": ["reflect"], "examples": ["White walls reflect more light than dark walls."]},
        "расширять": {"translations": ["broaden out", "expand"], "examples": ["The council decided to broaden the pavement", "Water expands as it freezes"]},
        "тушить огонь": {"translations": ["put out"], "examples": ["Put out the campfire before leaving"]},
    },
    
    "Существительные общего порядка": {
        "безделушка, пустяки": {"translations": ["triffle"], "examples": ["There's no point in arguing over trifles."]},
        "сознанание": {"translations": ["consciousness"], "examples": ["Surreal wisps of memory sifted back into his consciousness..."]},
        "совесть": {"translations": ["conscience"], "examples": ["Signore, I cannot in good conscience allow this to go any further"]},
        "пользователи интернета": {"translations": ["netizens"], "examples": ["A netizen shared a viral video on social media"]},
        "годовщина": {"translations": ["anniversary"], "examples": ["We are celebrating our anniversary next week"]},
        "дуга": {"translations": ["arc"], "examples": ["The island chain arcs from north to south"]},
        "резонанс": {"translations": ["resonance"], "examples": ["The island chain arcs from north to south"]},
        "исключение (удаление)": {"translations": ["exclusion"], "examples": ["Your essays tend to concentrate on one theme to the exclusion of everything else"]},
        "исключение": {"translations": ["exception"], "examples": ["Unfortunately there is an exception to every rule"]},
        "поместья":  {"translations": ["estates"], "examples": ["They had racked their estates"]},
        "гибкость": {"translations": ["flexibility"], "examples": ["He enjoyed the flexibility of his working arrangement"]},
        "ничтожество": {"translations": ["nonentity"], "examples": ["was so quiet he was almost a nonentity at the meeting"]},
        "ток": {"translations": ["current"], "examples": ["The current was measured in amperes"]},
        "средство": {"translations": ["mean"], "examples": ["The mean annual rainfall was 852 mm"]},
        "свободное время": {"translations": ["free time", "spare time", "leasure time"], "examples": ["This hobby occupies all of my free time"]},

    },
    
    "Государство, политика": {
        "воинская повинность": {"translations": ["conscription"], "examples": ["The conscription of 1813 has furnished 160,000 men"]},
        "военнослужающий": {"translations": ["service man"], "examples": ["the president is always guarded by secret service men"]},
        "вмешательство": {"translations": ["interference"], "examples": ["All over the world military men view any civilian interference with dislike"]},
        "обращаться": {"translations": ["appeal"], "examples": ["I appealed to the law of 1900"]},
        "вести переговоры": {"translations": ["negotiate"], "examples": ["We negotiated a fair price"]},
        "магистраль": {"translations": ["thoroughfare"], "examples": ["This may be noticed in any house which points on to a busy thoroughfare"]},
        "давно сложившаяся система": {"translations": ["edifice"], "examples": ["It looks as if the whole political edifice of the country is about to collapse"]},
        
    },
    
    "Отказ, согласие, отрицание, подтверждение": {
        "отказывать": {"translations": ["refuse", "turn down"], "examples": ["She refused to see him", "I can't turn down the offer of a free trip to Milan!"]},
        "отрицать": {"translations": ["deny", "repel"], "examples": ["Yes, I was there. I don't deny it", "His manners repel me"]},
    },
    
    "Цель, преследовать": {
        "цель": {"translations": ["objective"], "examples": ["She's expanding the business with the objective of improving efficiency"]},
    },
    
    "Время": {
        "уйти в анналы истории как": {"translations": ["go down"], "examples": ["This will go down as a day that changed everything"]},
        "кончать тем, что": {"translations": ["end up"], "examples": ["Much of this meat will probably end up as dog food"]}, 
        "продолжительный (нейтральный)": {"translations": ["prolonged", "lasting"], "examples": ["Prolonged exposure to the sun can cause skin cancer", "The reforms will bring lasting benefits"]}, 
        "затяжной": {"translations": ["protracted"], "examples": ["It was safer to let the Greeks grind each other down in a protracted conflict"]}, 
        "проходит время": {"translations": ["go by"], "examples": ["Saturday afternoons go by like lightning!"]}, 

    },
    
    "Перемещение": {
        "приходить": {"translations": ["arrive", "turn up"], "examples": ["He arrived home at six o'clock", "He didn't turn up? What a dirty trick!"]}, 
        "двигаться в направлении": {"translations": ["head towards"], "examples": ["We headed south towards the capital"]}
    },
    
    "Конструкция": {
        "не могу не": {"translations": ["can't but"], "examples": ["-"]}, 
    },
    
    "Здания": {
        "Большое здание":  {"translations": ["edifice"], "examples": ["Their head office was an imposing edifice"]}, 
    }
}

if __name__ == "__main__":
    print(sum([len(x[1]) for x in word_groups.items()]))
